conicoins = float(input())
print(f'I will get {conicoins * 2.98} RUB from the sale of {conicoins} conicoins.')
print(f'I will get {conicoins * 0.82  } ARS from the sale of {conicoins} conicoins.')
print(f'I will get {conicoins * 0.17 } HNL from the sale of {conicoins} conicoins.')
print(f'I will get {conicoins * 1.9622} AUD from the sale of {conicoins} conicoins.')
print(f'I will get {conicoins * 0.208} MAD from the sale of {conicoins} conicoins.')
